VPATH += :lib/acpi/components/utilities

SRCS += utaddress.c 	utalloc.c 	utcache.c 	utclib.c utcopy.c \
	utdebug.c utdecode.c 	utdelete.c 	uteval.c 	utexcep.c \
	utglobal.c utids.c utinit.c 	utlock.c 	utmath.c 	utmisc.c \
	utmutex.c utobject.c utosi.c 	utresrc.c 	utstate.c 	\
	uttrack.c utxface.c utxferror.c utxfinit.c 	utxfmutex.c

