VPATH += :lib/acpi/components/dispatcher

SRCS += dsargs.c dscontrol.c dsfield.c dsinit.c dsmethod.c \
	dsmthdat.c dsobject.c dsopcode.c dsutils.c dswexec.c \
	dswload2.c dswload.c dswscope.c dswstate.c

