

#include lib/acpi/components/debugger/Makefile
# include lib/acpi/components/disassembler/Makefile
include lib/acpi/components/dispatcher/Makefile
include lib/acpi/components/events/Makefile
include lib/acpi/components/executer/Makefile
include lib/acpi/components/hardware/Makefile
include lib/acpi/components/namespace/Makefile
include lib/acpi/components/parser/Makefile
#include lib/acpi/components/resources/Makefile
include lib/acpi/components/tables/Makefile
include lib/acpi/components/utilities/Makefile

