VPATH += :lib/acpi/components/namespace

SRCS += nsaccess.c nsalloc.c nsdump.c nsdumpdv.c \
	nseval.c nsinit.c nsload.c nsnames.c \
	nsobject.c nsparse.c nspredef.c nsrepair2.c \
	nsrepair.c nssearch.c nsutils.c nswalk.c \
	nsxfeval.c nsxfname.c nsxfobj.c

